const elections_list = [
    {
        id: 1,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2027-11-03",
        completed: false,
        winner: "To be announced...",
    },
    {
        id: 2,
        elections_type: "Presidential",
        elections_round: "2nd",
        elections_date: "2022-03-03",
        completed: true,
        winner: "Emmanuel Macron",
    },
    {
        id: 2,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2022-03-03",
        completed: true,
        winner: "Emmanuel Macron",
    },
    {
        id: 3,
        elections_type: "Presidential",
        elections_round: "2nd",
        elections_date: "2017-11-03",
        completed: true,
        winner: "Emmanuel Macron",
    },
    {
        id: 3,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2017-11-03",
        completed: true,
        winner: "Emmanuel Macron",
    },
    {
        id: 4,
        elections_type: "Presidential",
        elections_round: "2nd",
        elections_date: "2012-11-03",
        completed: true,
        winner: "François Hollande",
    },
    {
        id: 4,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2012-11-03",
        completed: true,
        winner: "François Hollande",
    },
    {
        id: 5,
        elections_type: "Presidential",
        elections_round: "2nd",
        elections_date: "2007-11-03",
        completed: true,
        winner: "Nicolas Sarkozy",
    },
    {
        id: 5,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2007-11-03",
        completed: true,
        winner: "Nicolas Sarkozy",
    },
    {
        id: 6,
        elections_type: "Presidential",
        elections_round: "2nd",
        elections_date: "2002-11-03",
        completed: true,
        winner: "Jacques Chirac",
    },
    {
        id: 6,
        elections_type: "Presidential",
        elections_round: "1st",
        elections_date: "2002-11-03",
        completed: true,
        winner: "Jacques Chirac",
    },

]

export default elections_list;